### ISSUE TITLE
Exclude elements from search

### ISSUE THREAD

**Issue by theodorosploumis** [DeuxHuitHuit/quicksearch#13]
Hi,

I am wondering if I could **exclude some elements** from being indexed/searched. For example, let's say we have the structure below and we need to get only the **text nodes** inside li but not the span elements.

```
<ul>
<li>Text here<span>(12)</span></li>
<li>Text here<span>(13)</span></li>
<li>Text here<span>(14)</span></li>
</ul>
```

**Comment by nitriques** [comment]
Yes you can, but you would need to make the thing searchable selectable via CSS selector and then use the the selector options.

Check this: https://github.com/DeuxHuitHuit/quicksearch#example-on-the-th-elements-on-a-table-row

Another option would be to customize the regexp to ignore things you do not want.

https://github.com/DeuxHuitHuit/quicksearch#callbacks

But IMO, it would really easier to add a simple DOM element to target the searchable text.
