### ISSUE TITLE
noResults element not shown on page-load

### ISSUE THREAD

**Issue by mariofink** [DeuxHuitHuit/quicksearch#23]
If the search input field already contains a value on page-load for which no results can be found, then the noResults element will not be shown.

**[Example on JSBin](http://jsbin.com/fehesu/edit?html,output)**

**Example source**
[noresults.txt](https://github.com/DeuxHuitHuit/quicksearch/files/195075/noresults.txt)

**Comment by nitriques** [comment]
Great find! As per #24, please submit a new PR!

**Comment by nitriques** [comment]
#25 should fix this!

**Comment by nitriques** [comment]
Fixed!
