### ISSUE TITLE
Integrating with other search elements.

### ISSUE THREAD

**Issue by christianmagill** [DeuxHuitHuit/quicksearch#27]
Are there any suggestions for integrating with other result limiting elements? I'd like to allow the user to also limit results by a few taxonomies that can be selected via multiple select2 elements.

**Comment by nitriques** [comment]
Would it be enough to add hidden span elements that contains the taxononies and just append the value of the select to the search input ?

**Comment by christianmagill** [comment]
That may not work the best as multiple items for a taxonomy could be selected as an OR condtion.

Is there any way to disable elements before applying the search?

**Comment by nitriques** [comment]
> Is there any way to disable elements before applying the search?

Yes. You cold provide your own implementation of `prepareQuery` or use a custom selector.

**Comment by christianmagill** [comment]
I couldn't quite get that to work, but I ended up making separate visibility classes for both my filter and search results so I could use CSS to display items that had the right combination of both. I then just used the show and hide methods to add/remove these classes.

**Comment by nitriques** [comment]
That's cool. I'll close the issue for now, but if you ever feel like sending a PR or reopening the issue, please do!

**Comment by christianmagill** [comment]
I'd like to reexamine your suggestions above.

If I used a custom selector would _quicksearch_ update the resulting elements each run through. The items would changed based on the other filtering.

How would you suggest using _prepareQuery_? I do my additional filtering via groups of checkboxes, and have a routine I use to determine which elements match the conditions.

**Comment by nitriques** [comment]
Sorry, but I do not fully understand what you mean by

> If I used a custom selector would quicksearch update the resulting elements each run through. The items would changed based on the other filtering.

> How would you suggest using prepareQuery? I do my additional filtering via groups of checkboxes, and have a routine I use to determine which elements match the conditions.

Yup! You can do pretty much anything you want in there.
