### ISSUE TITLE
Ignore rows with display:none

### ISSUE THREAD

**Issue by kczx3** [DeuxHuitHuit/quicksearch#30]
How can I ignore table rows that are hidden?  I tried the following:

`$('input#search').quicksearch('#table tbody tr:visible');`

But this doesn't have any affect.  The hidden rows just show up as soon as a match is found.

**Comment by nitriques** [comment]
Hi.
The :visible selector is terribly slow, I would try to avoid it at all cost.

I would use a data attribute for this. Just make sure that hidden items also have the attribute

```js
$('input#search').quicksearch('#table tbody tr:not([data-ignore])');
```
