### ISSUE TITLE
Uncaught TypeError: window.clearTimeout is not a function

### ISSUE THREAD

**Issue by FDiskas** [DeuxHuitHuit/quicksearch#32]
![gnome-shell-imgur-jlqlny](https://cloud.githubusercontent.com/assets/468006/18341396/7947f016-75b2-11e6-8e68-6b6ac6f6acd5.png)

**Comment by nitriques** [comment]
Which builder to you use ? just npm ?

**Comment by FDiskas** [comment]
Yes.

**Comment by nitriques** [comment]
Hum. Do you get the bug here as well ? https://deuxhuithuit.github.io/quicksearch/r/examples/ ?

**Comment by FDiskas** [comment]
This bug is only then this is requered by node.
Blablabla import from blablabla;

**Comment by nitriques** [comment]
Can you send a PR with only [this](https://github.com/FDiskas/quicksearch/commit/55b5cff9d42765e84d1b66eb73702eab40545b26#diff-e6df47045346ad5e0905c2d63d439f06L338) modification please ? It fixes this bug right ?

**Comment by FDiskas** [comment]
Yes i did. And it works. Right now im ysing my fork

**Comment by nitriques** [comment]
I've never seen something like this, that really odd. Underscore js uses the same pattern and it does works on both places...

**Comment by nitriques** [comment]
@FDiskas version 2.3.1 is up on npm. Thanks! If you want to continue to improve it or fix bugs, please go ahead an submit other PRs (but try to make them small and atomic).
