### ISSUE TITLE
Can this be used for data that's not in a list/table?

### ISSUE THREAD

**Issue by seanvree** [DeuxHuitHuit/quicksearch#38]
Hey dudes!

Can this be used to search data that is populated on a static HTML file that's populated from an external file (log)?

We are thinking of implementing this into our tool Logarr:  https://github.com/seanvree/logarr

We need it to do EXACTLY as it appears on your examples, but our data is NOT in a table, it's a simple DIV.  

Take a look at our project and let me know!

THANKS!

**Comment by nitriques** [comment]
@seanvree yes it should work, as long as you can isolate a record in a html element. Check the selector options https://github.com/DeuxHuitHuit/quicksearch#options
