### ISSUE TITLE
Accent neutralization

### ISSUE THREAD

**Issue by Tokata36** [DeuxHuitHuit/quicksearch#41]
Hello,

Please do you know how can I neutralize accent for searching?

Thank you very much for any help.

**Comment by DaniloRJBR** [comment]
Estou com o mesmo problema!

**Comment by nitriques** [comment]
There is already an option to get rid of the accents:

https://github.com/DeuxHuitHuit/quicksearch/blob/master/src/jquery.quicksearch.js#L16

https://github.com/DeuxHuitHuit/quicksearch#options

Set removeDiacritics to false.
