### ISSUE TITLE
Não considerar acentos na pesquisa. ignorar acento!

### ISSUE THREAD

**Issue by DaniloRJBR** [DeuxHuitHuit/quicksearch#42]
Primeiro, parabéns! O plugin esta funcionando bem.

Somente gostaria que ele ignora-se os acentos.
Exemplo: Exibir o mesmo resultado eu digitando Suecia ou Suécia.

Help

*EDIT:* Add translation from google translate

First, congratulations! The plugin is working fine.

I just wish he ignored the accents.
Example: Display the same result by typing Suecia or Suécia.

Help

**Comment by nitriques** [comment]
Thanks ! 

There is already an option to get rid of the accents:

https://github.com/DeuxHuitHuit/quicksearch/blob/master/src/jquery.quicksearch.js#L16

https://github.com/DeuxHuitHuit/quicksearch#options

Set `removeDiacritics` to `false`.
